### ISSUE TITLE
Write test suite for pipeline

### ISSUE THREAD

**Issue by cdebourcy** [chanzuckerberg/idseq-pipeline#111]
2 input files
1 input file

**Comment by boris-dimitrov** [comment]
This is good for top level integration tests.   Also need testing of individual complicated functions, at unit/function level.  See for example one way to do it in validate_linage in common.py.  In those cases the tests can also serve as executable documentation.  Tests like that in general represent a contract between implementor and user;  so when using a function you make an assumption about how it works, you write down your assumption in the form of a test.  Then someone comes in and refactors the implementation;  your test will make sure your assumption as a user of the function is not broken.
