### ISSUE TITLE
add logic to app/jobs/autoscaling.py to set min_capacity for batch compute environments

### ISSUE THREAD

**Issue by boris-dimitrov** [chanzuckerberg/idseq-pipeline#162]
the script already works very well for the autoscaling groups for rapsearch and gsnap

the problem with batch is that it doesn't seem to automatically expand or collapse its compute environments so if we do nothing there could be dozens of jobs stuck in runnable for hours and conversely when all is finished there could be dozens of instances idling in the compute environment and only 4 jobs running --- so to address this, quite simply,  with every invocation of the script, we should set the min capacity and the desired capacity on the compute environment for queue  idseq_himem to #runnable + #running jobs there;   and similarly for queue idseq.

**Comment by boris-dimitrov** [comment]
Btw this is something I've been doing manually a few times a day.    Just automate it.

**Comment by cdebourcy** [comment]
Cool, planning to do this on Monday!
