### ISSUE TITLE
Samples https://idseq.net/samples/3274 and https://idseq.net/samples/3272 are failing 

### ISSUE THREAD

**Issue by eggerdesigns** [chanzuckerberg/idseq-pipeline#165]

**Comment by boris-dimitrov** [comment]
In particular note that, as stated in #145, rerunning doesn't help.   CD-HIT-DUP can't handle these samples.  Unclear if memory issue or something else.

**Comment by boris-dimitrov** [comment]
See also https://github.com/chanzuckerberg/idseq-pipeline/issues/164
