### ISSUE TITLE
correct input file truncation for fasta format

### ISSUE THREAD

**Issue by boris-dimitrov** [chanzuckerberg/idseq-pipeline#177]
The fastq format always has 4 lines per record. The fasta format allows the the sequence to be split over multiple lines, so the records could potentially have variable numbers of lines.

cc @cdebourcy

**Comment by boris-dimitrov** [comment]
There are also other places in the pipeline where we assume FASTAs are single sequence line per read id line, but perhaps there that assumption is justified, considering those are output by our own SAM to Fasta converter?

**Comment by cdebourcy** [comment]
Yes, the other FASTAs satisfy that assumption because we generated them ourselves
