### ISSUE TITLE
roll up all taxonomy levels in pipeline

### ISSUE THREAD

**Issue by boris-dimitrov** [chanzuckerberg/idseq-pipeline#179]
turns out this will greatly simplify the tree viz

right now pipeline only handles species, genus, family

it's best to do this in one place rather than replicate this code in pipeline, rails, and JS

for an idea of the complexity this saves, see function fill_missing_calls_tests

cc @cdebourcy @jshoe

**Comment by cdebourcy** [comment]
Agree 1000%
