### ISSUE TITLE
Style Changes

### ISSUE THREAD

**Issue by yunfangjuan** [chanzuckerberg/idseq-pipeline#185]
1. Getting rid of run_and_log (only checking the lazy_run) 
2.  Make the whole step atomic. Save to stats file at each step.  No need to recount during lazy run. Make sure web load doesn't get triggered . https://github.com/chanzuckerberg/idseq-pipeline/blob/30e0e74eb018241845d4ec7f5f378682585952c2/idseq_pipeline/commands/host_filtering_functions.py#L672

**Comment by yunfangjuan** [comment]
* Make all the run_* functions to include (input_files, output_files, ...)

**Comment by yunfangjuan** [comment]
* need better documentation for  call_hits_m8

**Comment by yunfangjuan** [comment]
https://github.com/chanzuckerberg/idseq-pipeline/blob/30e0e74eb018241845d4ec7f5f378682585952c2/idseq_pipeline/commands/common.py#L693 
Make the clean_tax_ids function clearer of its purposes.

**Comment by cdebourcy** [comment]
Samples to test on (provided by Boris):
https://idseq.net/samples/3889
https://idseq.net/samples/4000
https://idseq.net/samples/3920
https://idseq.net/samples/3006
https://idseq.net/samples/4
https://idseq.net/samples/2981
