### ISSUE TITLE
performance of stool samples -- immediate fix needed

### ISSUE THREAD

**Issue by boris-dimitrov** [chanzuckerberg/idseq-pipeline#195]
the current pipeline fails to complete host filtering even after 24 hours due to gsnap's inability to handle inputs of that size even running in a 240GB 32vCPU docker container

skipping the gsnap host filter step makes it possible for those jobs to complete just fine!   see, for, example sample 4000

suggestion (boris):  move subsampling up a step so it happens before the gsnap host filter

suggestion 2 (yunfang):  move gsnap down a few steps but still run it in a docker container, this time the 120GB 16vCPU container for stage 2

suggestion 3 (boris):  run gsnap host filter on the gsnap tier

Discussion:  Boris fears suggestion 2 will have performance and complexity repercussions.   Yun Fang believes that it wouldn't.

Why we need to consider a fix urgently.   Without a fix, these samples may go on for many days, instead of several hours, in host filtering.   The way our system currently works, this would hold up the gsnap and rapsearch tiers at max during all this time.   This would likely cost $20-$30k if it goes on for 3-4 days.

[aside:  It has been proposed we change how autoscaling works to only accommodate jobs that have already reached stage 2, which would mitigate that cost overrun quite a bit.    There is, however, a downside -- instability during scale in.   We can initiate scale in as soon as there are no jobs in stage 2, but right then jobs can start entering stage 2 and dispatching to instances that are going away, then crashing.   This doesn't happen now because we consider jobs at stages 1+2 so if a job is about to transition to stage 2 it has been counted already making sure to prevent the tiers from scaling in.  There are of course numerous other ways to solve this but seems like that should go into the pipeline manager we are designing.]

cc @cdebourcy @jshoe @jameshowardwang

**Comment by boris-dimitrov** [comment]
I am actually changing my mind about autoscaling basing its decisions only stage 2 jobs.   Probably worth doing that after all, but setting min capacity to 1 for both tiers so developer productivity doesn't suffer.   The reason is that I see a lot of very big jobs with tons of reads post star these days;  no longer reasonable to expect that host filtering would finish in 20min;  more like hours.

**Comment by boris-dimitrov** [comment]
People keep submitting samples that are 75+ mil nonhost reads.   Several running just now, e.g. https://idseq.net/samples/4084,  and I don't expect those to succeed without skipping gsnap host filter or doing something about it.

**Comment by yunfangjuan** [comment]
I think suggestion 3 is harder to setup/deploy because we will need to re-deploy the gsnap tier every time there's a change (i.e. adding mosquitos/..) and it also competes with the existing gsnap resources which could behave quite differently. I think for simplicty reasons, if we could live with #2, why do #3? 

I temporarily disabled gsnap_filter for any sample with more than 10M unmapped reads after bowtie. and I will put in another fix (#2) above.
