### ISSUE TITLE
review/fix package structure of idseq-pipeline

### ISSUE THREAD

**Issue by boris-dimitrov** [chanzuckerberg/idseq-pipeline#30]
The packaging code here, pasted from the `skele-cli` project, makes liberal use of `import *` and other textbook examples of module system abuse, with the net effect of making the resulting package brittle in subtle ways.   Let's have it reviewed by someone with more Python packaging experience.   cc @ttung @cdebourcy

**Comment by boris-dimitrov** [comment]
A starting point for morphing this into a saner solution.   Remove the really strange code-walking in cli.py and put the "foo_function" and "foo" modules together, so we can get rid of these compilation warnings:
```
bdimitrov@ip-172-31-22-217:~/idseq-pipeline$ python idseq_pipeline
idseq_pipeline/commands/host_filtering.py:7: SyntaxWarning: import * only allowed at module level
  def run(self):
idseq_pipeline/commands/non_host_alignment.py:7: SyntaxWarning: import * only allowed at module level
  def run(self):
idseq_pipeline/commands/postprocess.py:7: SyntaxWarning: import * only allowed at module level
  def run(self):
idseq_pipeline/commands/host_indexing.py:7: SyntaxWarning: import * only allowed at module level
  def run(self):
idseq_pipeline/commands/gsnap_indexing.py:7: SyntaxWarning: import * only allowed at module level
  def run(self):
idseq_pipeline/commands/rapsearch_indexing.py:7: SyntaxWarning: import * only allowed at module level
  def run(self):
idseq_pipeline/commands/lineages.py:7: SyntaxWarning: import * only allowed at module level
  def run(self):
idseq_pipeline/commands/blacklist.py:7: SyntaxWarning: import * only allowed at module level
  def run(self):
```

**Comment by ttung** [comment]
Can't you just move those imports to the top of the module?

**Comment by boris-dimitrov** [comment]
Oh thanks @ttung !

**Comment by cdebourcy** [comment]
When I tried it, early on, that didn't actually work, but maybe I was missing something. It only allowed "import *" within the class underneath.

**Comment by ttung** [comment]
Probably had circular imports. If you run into that, I can help you resolve that.

**Comment by cdebourcy** [comment]
Oh ok! Thanks @ttung
