### ISSUE TITLE
correctness of lzw_fraction computation

### ISSUE THREAD

**Issue by boris-dimitrov** [chanzuckerberg/idseq-pipeline#68]
I don't know what this is supposed to compute but the line `dictionary[c] = dict_size` looks highly suspicious because `dict_size` at that point is not the dictionary size.  :P)

```
def lzw_fraction(sequence):
    if sequence == "":
        return 0.0
    sequence = sequence.upper()
    dict_size = 0
    dictionary = {}
    # Initialize dictionary with single char
    for c in sequence:
        dict_size += 1
        dictionary[c] = dict_size
    word = ""
    results = []
    for c in sequence:
        wc = word + c
        if dictionary.get(wc):
            word = wc
        else:
            results.append(dictionary[word])
            dict_size += 1
            dictionary[wc] = dict_size
            word = c
    if word != "":
        results.append(dictionary[word])
    return float(len(results))/len(sequence)
```

**Comment by boris-dimitrov** [comment]
I see now that the values stored in the dictionary are not used.

Anyway I think this similar algorithm represents better compression :P )   I would appreciate some explanation of why are we using the specific algorithm above instead of say the one below or any number of similar algorithms.   Very small perturbations in these algorithms (e.g. changing `word = c` to "word = ""` above) can result in big changes in "compression" ratios.
```
#!/usr/bin/env python
import sys

def lzw_fraction(sequence):
    s = set()
    w = ''
    for c in sequence:
        w += c
        if w not in s:
            print(w)
            s.add(w)
            w = ''
    return float(len(s)) / len(sequence)

if __name__ == "__main__":
    print(lzw_fraction(sys.argv[1]))
```

**Comment by boris-dimitrov** [comment]
```
(aeon) ./lzw.py "aababcabcdabcdeabcdefabcdefgabcdefghabcdefghi"                                                                                                                              Fri 6:48pm
a
ab
abc
abcd
abcde
abcdef
abcdefg
abcdefgh
abcdefghi
0.2
```

**Comment by boris-dimitrov** [comment]
Btw my concern here was twofold.   First, correctness is important in its own right, obviously.   Second, this is a piece of python that takes 2-3 minutes even on small samples (~1GB fastq.gz) and we could easily make it much faster.

**Comment by boris-dimitrov** [comment]
Note from Charles is the current pipeline code matches the DeRisi lab reference implementation.

**Comment by yunfangjuan** [comment]
s3://czbiohub-infectious-disease/ngs_scripts/lzw-filter-v1.0.php

**Comment by yunfangjuan** [comment]
https://rosettacode.org/wiki/LZW_compression#Python 

Our implementation is almost exactly the same as the rosettacode. There's a slight bug in our current for scanning through the sequence to build the initial dictionary but it doesn't actually affect the results.

**Comment by boris-dimitrov** [comment]
Agreed that it doesn't affect results.   If we want the exact same behavior, the pythonic implementation is this:
```
def lzw_fraction(sequence):
    s = set(sequence)
    w = ''
    for c in sequence:
        w += c
        if w not in s:
            s.add(w)
            w = c   # i wish this was w = '', --boris
    if w not in s:
        s.add(w)
    return float(len(s)) / len(sequence)
```
I annotated the line above where I can't say I agree with the reference, but don't mind preserving the proven behavior.

With this rewrite, and parallelizing, we should have good speed up.

**Comment by yunfangjuan** [comment]
Hm I don't think this works. 

>>> def lzw_fraction(sequence):
...     s = set(sequence)
...     w = ''
...     for c in sequence:
...         w += c
...         if w not in s:
...             s.add(w)
...             w = c   # i wish this was w = '', --boris
...     if w not in s:
...         s.add(w)
...     return float(len(s)) / len(sequence)
...
>>> lzw_fraction("actg")
1.75

**Comment by yunfangjuan** [comment]
Current implementation: 

>>> def compress(uncompressed):
...     # Build the dictionary.
...     dict_size = 0
...     dictionary = {}
...     w = ""
...     result = []
...     for c in uncompressed:
...         if not dictionary.get(c):
...             dictionary[c] = dict_size
...             dict_size += 1
...     for c in uncompressed:
...         wc = w + c
...         if wc in dictionary:
...             w = wc
...         else:
...             if w:
...                 result.append(dictionary[w])
...             # Add wc to the dictionary.
...             dictionary[wc] = dict_size
...             dict_size += 1
...             w = c
...
...     # Output the code for w.
...     if w:
...         result.append(dictionary[w])
...     return (result, dictionary)
...
>>> compress("actg")
([0, 1, 2, 3], {'a': 0, 'c': 1, 'g': 3, 'ac': 4, 't': 2, 'tg': 6, 'ct': 5}) 

It would give you 1 back.

**Comment by yunfangjuan** [comment]
>>> x = "actgtgaaactgaattccgg"
>>> float(len(compress(x)[0]))/len(x)
0.8
>>> lzw_fraction(x)
0.95

**Comment by boris-dimitrov** [comment]
Yeah I see one unintended difference, I wrote `if w not in s:  s.add(w)` but actually in the original code it's `if w: s.add(w)` which is super bogus because it's only checking if the loop made at least one iteration.

**Comment by yunfangjuan** [comment]
it doesn't sound so bogus to me basically the original lzw code. w is the word from previous round. 
it does result.append(dictionay[w]) when w was set in the else branch.

**Comment by boris-dimitrov** [comment]
What you say makes sense, and I will study this some more, looking at the decompress function.
