### ISSUE TITLE
correctness bug:  Same sample, two consecutive runs with SAME code, different results after stage 1

### ISSUE THREAD

**Issue by boris-dimitrov** [chanzuckerberg/idseq-pipeline#72]
The number of non-host reads is 250,578 in sample 1309 and 237,850 in sample 1310, but the two samples are based on uploading the exact same input fastq.gzs.

cc @cdebourcy @yunfangjuan @eggerdesigns

**Comment by boris-dimitrov** [comment]
From the logs it seems the difference is introduced by STAR, within the first minute of STAR execution.  Compare log line from 07:03:42 vs 02:04:55 in https://us-west-2.console.aws.amazon.com/cloudwatch/home?region=us-west-2#logEventViewer:group=/aws/batch/job;stream=aegea_batch/default/13447011-0331-448b-b995-6a565ab11e4c vs https://us-west-2.console.aws.amazon.com/cloudwatch/home?region=us-west-2#logEventViewer:group=/aws/batch/job;stream=aegea_batch/default/5f339ef1-e05b-4526-b2ab-b84b20db12a7

**Comment by boris-dimitrov** [comment]
My guess is that STAR could be... improved...

**Comment by boris-dimitrov** [comment]
I reran the same sample through localhost (same pipeline, master webapp) and got numbers after stage 1 to be exactly the same as sample 1309 in prod.    The Z scores and aggregate scores are different because the backgrounds are different, which is totally fine.  This makes sample 1310 from prod look like an aberration.  But it's only 2 out of 3 so far.

**Comment by yunfangjuan** [comment]
According to Joe, the STAR may have different output for each run because of some inherent randomness. But they are supposedly statistically equivalent.

**Comment by boris-dimitrov** [comment]
We've since confirmed STAR is buggy, esp with many threads.   So I guess we can close this issue.
