### ISSUE TITLE
stack trace in host filtering generate_unmapped_singles_from_sam

### ISSUE THREAD

**Issue by boris-dimitrov** [chanzuckerberg/idseq-pipeline#84]
https://us-west-2.console.aws.amazon.com/cloudwatch/home?region=us-west-2#logEventViewer:group=/aws/batch/job;stream=aegea_batch/default/8c49d00a-abde-44f8-a93f-e7fe8843635d

while line[0] == '@':
IndexError: string index out of range

**Comment by cdebourcy** [comment]
The output from LZW filter was empty. This was a public sample from EBI Metagenomics

**Comment by boris-dimitrov** [comment]
Got it.   We just have to make the pipeline robust against everything getting filtered out at any point.

**Comment by cdebourcy** [comment]
Ok. Will do that
